theme = "onelight"

[editor]
# cursorline = true
# bufferline = "multiple"
# auto-info = false
auto-save = true
auto-pairs = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
# render = true

[editor.lsp]
auto-signature-help = false
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal.space]
w = ":w" # Save
