theme = "ayu_light"

[editor]
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
auto-signature-help = false

[editor.soft-wrap]
enable = true

[keys.normal.space]
w = ":w" # Save
