[[language]]
name = "typescript"
file-types = ["ts","js"]
language-server = { command = "deno", args = ["lsp"]}
config = { deno = { enable = true, lint = true } }
auto-format = true

[[language]]
name = "tsx"
file-types = ["tsx","jsx"]
language-server = { command = "deno", args = ["lsp"]}
config = { deno = { enable = true, lint = true } }
auto-format = true
